xrun \
    -gui \
    -debug \
    -linedebug \
    $WORK_DIR/tb/tb_schedule.sv \
    $WORK_DIR/rtl/dsb_pkg.sv \
    $WORK_DIR/rtl/schedule.sv \
    $WORK_DIR/rtl/dotprod_phase2.sv \
    $WORK_DIR/rtl/xnor_phase1.sv \
    $WORK_DIR/rtl/compute_tile.sv \
    $WORK_DIR/rtl/8t_bitcell.sv \